# Generated by Django 5.2.10 on 2026-01-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritePost',
        ),
    ]
