# Generated by Django 5.2.10 on 2026-01-28 10:13
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_post_tags'),
    ]
    operations = [
        TrigramExtension()
    ]
